stages:
  - stage: Build
    displayName: Build Fasza
    jobs:
      - job: MavenPackageandPub
        displayName: package and publish
        steps:
        - task: Maven@3
          displayName: package
          inputs:
            mavenPomFile: 'pom.xml'
            publishJUnitResults: true
            testResultsFiles: '**/surefire-reports/TEST-*.xml'
            javaHomeOption: 'JDKVersion'
            mavenVersionOption: 'Default'
            mavenAuthenticateFeed: false
            effectivePomSkip: false
            sonarQubeRunAnalysis: false